name: Project Hackthon CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Check php
      run: php --version

    - name: install phpcs
      run: |
        composer require --dev automattic/vipwpcs dealerdirect/phpcodesniffer-composer-installer
        vendor/bin/phpcs -i
      
    - name: Run phpcs
      run: vendor/bin/phpcs --standard=WordPress wp-content/themes/twentytwentyone/*.php
      
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          cd ${{ secrets.PATH }}
          git pull origin
    - name: Send mail
      if: failure()
      uses: dawidd6/action-send-mail@v2
      with:
        # mail server settings
        server_address: smtp.mailgun.org
        server_port: 587
        # user credentials
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        # email subject
        subject: ${{ github.job }} job of ${{ github.repository }} has ${{ job.status }}
        # email body as text
        body: ${{ github.job }} job in worflow ${{ github.workflow }} of ${{ github.repository }} has ${{ job.status }}
        # comma-separated string, send email to
        to: ankitgsolanki@gmail.com,ronak.ganatra@multidots.com
        # from email name
        from: GitHub
