name: PHP Composer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Check php
      run: php --version

    - name: install phpcs
      run: |
        composer require --dev automattic/vipwpcs dealerdirect/phpcodesniffer-composer-installer
        vendor/bin/phpcs -i
      
    - name: Run phpcs
      run: vendor/bin/phpcs --standard=WordPressVIPMinimum wp-content/themes/twentynineteen/*.php
